### PR TITLE
Enable function has container parameter for runtime definition

### PR DESCRIPTION
**Pull request by maxetime**

### CODE REVIEW

**Comment by mislav** [comment]
What is the use case for this? Can't you programatically determine the container element before invoking `$.pjax` function?

**Comment by maxetime** [comment]
When you use pjax for all links, but depending on the state of your page/app you load the content in a different container.

**Comment by mislav** [comment]
That makes sense. Why did you close the PR?

**Comment by maxetime** [comment]
The call to verify the container is done too early in the process and so it would need access to some data that is set later. I'll try to find a way to get this data at call time.

**Pull request closed without merging**
