### PR TITLE
Added pjax:beforeReplace cancel

### PR DESCRIPTION
**Pull request by jspizziri**
Added the ability to cancel pjax on the pjax:beforeReplace event.

### CODE REVIEW

**Comment by jvivs** [comment]
I'll add a :+1: for the opportunity to cancel `pjax:beforeReplace` event.

I'm relatively new to ajax, but I've run around the history API a few times in the past.

This time around, my particular use case is pjax-enabled filtering of search results. 

When a filter ends up with 0 results, we'd like to display a dialog and let the user undo the last filter selection. Before implementing ajax, we needed to implement custom state handling for these message dialogs. With history support, it's as easy as `window.history.back()` to restore the last valid filter.

I've added a variation of the initially suggested fix in my fork here: https://github.com/jvivs/jquery-pjax/commit/7773003c02f2b5dd379778fec939749861761443. Seems a bit nicer to opt out of the subsequent DOM updates when canceling `pjax:beforeReplace`, but still fire the `pjax:complete` event. It's somewhat along the lines of expected behavior of a plugin that wraps `$.ajax`.

After looking a bit closer, it ultimately might make more sense if a cancelable `pjax:beforeReplace` was fired here instead: https://github.com/jvivs/jquery-pjax/blob/master/jquery.pjax.js#L283. If we run into problems or come up with improvements, I'll swing back.

Thanks for such a solid library! It's a real breath of fresh air compared to dealing with the cross-browser quirks that come with the native history API.

**Comment by mislav** [comment]
> When a filter ends up with 0 results, we'd like to display a dialog and let the user undo the last filter selection.

Why can't that special dialog and undo button be returned by the server in case of 0 results? Then you don't have to special-case this in your frontend.

**Comment by jvivs** [comment]
@mislav Thanks for the quick reply! 

It's a solution, sure. Unfortunately not as friendly for the user.  

Updating the pjax container in entirety removes the previous filtered content, and thus the user's searching context. If `pjax:beforeRender` were cancelable, a developer would be able to opt-out of an update--in this case retain the previous context but display a dialog overlaying the content.

In order to get around those UX hangups and still take your suggestion, it would require return the previous filtered results beneath the dialog with the new url--breaking the RESTfulness of the newly-updated url.

Maybe I'm missing something, but what's the argument against being able to opt-out of a DOM manipulation? I've cruised a bunch of the pull requests surrounding this issue and it's not immediately clear how it's a bad or over-complex pattern. 

I've also cruised through the pjax event flow and can't seem to find another good/better entry-point where a developer could opt out of the update if it is unsatisfactory.

**Comment by mislav** [comment]
My reasons are in [my comments above](https://github.com/defunkt/jquery-pjax/pull/428#issuecomment-67709166).

**Comment by jspizziri** [comment]
was any equivalent functionality every implemented?

**Comment by mislav** [comment]
@jspizziri No, sorry. Working on the next big version of pjax, though.

**Comment by jvivs** [comment]
You can use my fork if you'd like.

**Comment by jspizziri** [comment]
@jvivs,

Thank you, I actually have a fork of my own though, I'd just prefer to use the maintained project.

**Comment by IvoPereira** [comment]
Too bad this PR was not merged.

Gonna use your fork @jspizziri. Thanks for providing an alternative!

**Comment by jtheck** [comment]
Any word on intercepting a "back" request?

I've got a couple strictly client-side "pages" that I like to show, which replace my pjax-container (I just make it invisible to make room) - I would like to catch the "back" request to re-display the pjax-container before actually going back.

If I could preventDefault or return false from "pjax:beforeReplace" that would be super useful.

Thanks! Love the plugin.

**Comment by RichardTMiles** [comment]
So is this a feature? could we get it documented on the readme? ;)

**Comment by qooob** [comment]
Is there a way to modify inserting content using `beforeReplace` or some other way?

I need to remove `<script>` tag from certain way? I know how to remove it from the response but I'm not sure how to pass the changes to _PJAX_?

**Pull request closed without merging**
