### PR TITLE
Readme Changed

### PR DESCRIPTION
**Pull request by imrealashu**

### CODE REVIEW

**Comment by mislav** [comment]
I'm sorry, what is this pull request for?

**Comment by samdark** [comment]
It's our fork. Not sure why it was pull requested... I guess you can close it.

**Comment by mislav** [comment]
@samdark I'm guessing it was opened in error, or someone is just experimenting with GitHub. Did you receive a notification about this PR? Do you usually watch this repo, or did GitHub start sending you notifications about this thread because your commits are present in the PR?

**Comment by LAV45** [comment]
I follow your PR, and told a friend about the miracle commit ))

**Comment by samdark** [comment]
Yep, it was @LAV45 who told me.

**Pull request closed without merging**
