### PR TITLE
Add automatically generated change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags and labels for issues in your repo.

And special for such cases - I created a [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), that generate change log file based on **tags**, **issues** and merged **pull requests** (and split them to separate lists according labels) from :octocat: GitHub Issue Tracker.

By using this script your Change Log will look like this: [Click me!](https://github.com/skywinder/jquery-pjax/blob/add-change-log-file/CHANGELOG.md)

> ***What’s the point of a change log?***
To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.
> :copyright: *[http://keepachangelog.com](http://keepachangelog.com/)*

And now you do not need to spend a lot of :hourglass_flowing_sand: for filling it manually!

Some essential features of **github_changelog_generator**:

- Generate **neat** Change Log file according basic [change log guidelines](http://keepachangelog.com). :gem:

- **Distinguish** issues **according labels**:
    - Merged pull requests (all `merged` pull-requests)
    - Bug fixes (by label `bug` in issue)
    - Enhancements (by label `enhancement` in issue)
    -   Issues (closed issues `w/o any labels`)

-  it **exclude** not-related to changelog issues (any issue, that has label `question` `duplicate` `invalid` `wontfix` )  :scissors:

- You can set which labels should be included/excluded and apply a lot of other customisations, to fit changelog for your personal style :tophat: (*look `github_changelog_generator --help`  for details)*

You can easily update this file in future by simply run script: `github_changelog_generator defunkt/jquery-pjax` in your repo folder and it make your Change Log file up-to-date again!

Since now you do not have to fill your `CHANGELOG.md` manually: just run script, relax and take a cup of :coffee: before your next release!

Hope you find this commit as useful. :wink:

### CODE REVIEW

**Comment by mislav** [comment]
Hi, thank you for your suggestion, but I won't accept it in this instance.

Like everyone, I like seeing details of what changed between releases. But, I personally don't like maintaining CHANGELOG files:

* https://github.com/sstephenson/ruby-build/pull/545
* https://github.com/sstephenson/rbenv/pull/688

They're a hassle to maintain constantly and often fall out of date.

Your script automates the process of compiling changelogs by hand; that's great. But, I also find generated changelogs (either from git commits or issues/PR information) to be of lower quality than if they were manually made. This is because issue/PR subject lines are sometimes not full sentences and might not describe what was changed very well.

I write changelogs by first generating them from git history, filtering only files/directories that may contain implementation files (and not tests, etc):

```sh
git log --no-merges --reverse \
  --format='%C(auto,green)* %s%C(auto,reset)%n%w(0,2,2)%+b' \
  v1.0.0..v1.0.1 -- lib src
```

Then I paste that [into Releases](https://github.com/defunkt/jquery-pjax/releases) as a draft and clean it up, often splitting into sections like "Bug fixes", "Optimizations", "New Features".

I believe that humans would [prefer to read manually-made release notes](https://github.com/github/hub/releases/tag/v1.11.0) rather than something auto-generated. Also, the reason why I like GitHub Releases is that I can edit and format release information even after the release is tagged. You can't do that if you distribute release notes in version control.

**Comment by skywinder** [comment]
@mislav  Got it. Thanks for your feedback!

**Comment by PascalPrecht** [comment]
Just one note to:

> I believe that humans would prefer to read manually-made release notes rather than something auto-generated

When git commit messages are written properly (by humans) then you also get sort of "manually" made release notes. All information about bug fixes, features and breaking changes should be in a commit message anyway. So extracting/generating based on that information sounds more dry and productive to me. But again, just a personal opinion I'd like to leave here :)

**Comment by mislav** [comment]
> When git commit messages are written properly (by humans) then you also get sort of "manually" made release notes. All information about bug fixes, features and breaking changes should be in a commit message anyway.

Sure, in an ideal world. [I try to write concise, descriptive subject lines myself](http://mislav.uniqpath.com/2014/02/hidden-documentation/) and provide background, rationale and potential pitfalls all in the commit message. However, not all contributors do the same. Since it's impossible for me to go back and amend the commit messages of all contributions since the last release, I rather curate the list of changes myself in a language that I prefer.

**Comment by skywinder** [comment]
@mislav just some notes about:
GitHub Releases is a very good thing. And it's very good practice to maintain it (not so much people using it yet)! :congratulations:  

I'm not try to compare quality of auto-generated and manually generated logs.
But want to notice:

The Changelog like this sometimes really helps. For example:

When I found a closed bug - it's very useful to understand, in which release it was fixed. In that case you can easily find this issue by \# in `CHANGELOG.md`.

- it's not so quite easy to find it in manually filled Releases notes.
- this file can also help you to build your Release note and not miss features in manually-filled list.

In the end:

I think, that GitHub Releases is more for end-users.
But `CHANGELOG.md` could stay in the repo for developers with detailed list of changes.
And it's nothing bad to combine GitHub Releases and CHANGELOG.md file together in that manner.

Of course - it's up to you, how you would like to maintaining change logs. 
Is's JMHO, I am in no case not impose it to you.

Just want to make GithHub repos better with this :smiley:

**Comment by mislav** [comment]
> When I found a closed bug - it's very useful to understand, in which release it was fixed. In that case you can easily find this issue by # in CHANGELOG.md.

Sure. What I do is try to link the closed bug to the commit or pull request where it was fixed. GitHub's commit view will show you which of the tagged versions include that commit. For instance, if "1.6.0, 1.5.4, 1.5.3" are listed, then you know that "1.5.3" is the earliest tagged version that includes this fix. This method of lookup is much faster than trying to figure it out from release notes or CHANGELOG.

> Just want to make GithHub repos better with this

Yeah, I'm pretty sure that maintainers of some other projects will be pleased with this tool so they have less work to do manually!

**Pull request closed without merging**
