### PR TITLE
fixed jquery.ready before script file loaded

### PR DESCRIPTION
**Pull request by page7**
fixed jquery.ready before script file loaded

### CODE REVIEW

**Comment by mislav** [comment]
Hi, I don't understand at all what this does. Maybe some explanation is in order? How about tests? Which use case does this solve? Can you share sample code?

**Comment by page7** [comment]
ok, like this:
```
<link href="/css/chosen.css" rel="stylesheet" />
<script src="/js/jquery.chosen.js"></script>
<script type="text/javascript">
$(function(){

    $(".ui-select").chosen();  // chosen is a plugin, page is here: https://github.com/harvesthq/chosen

});
</script>
```

If i use $.ajax and $.html to load this code. everything is ok.
But in pjax. `$(".ui-select").chosen();`  will throw that : `Uncaught TypeError: $(...).chosen is not a function`

**Comment by staabm** [comment]
@page7 and how does that relate to pjax?

**Comment by page7** [comment]
@staabm Sorry, i don't know how to use pjax in jsfiddle. so i create a new repository.
https://github.com/page7/jquery-pjax-test

**Comment by mislav** [comment]
@page7 Thanks, now I understand much better.

You were definitely bitten by #331 and we're aware of this. Inline scripts will execute immediately while external scripts will be loaded async (as opposite of sequential load during normal page load).

I won't make this change, because it's a hacky workaround for a specific problem that only covers jQuery, but wouldn't solve other libraries who might attach DOMContentLoaded handlers manually and not through jQuery. Also, overriding bits of jQuery seems like a slippery slope.

The solution would be to ensure that `jquery.chosen.js` plugin is loaded site-wide at first page load, i.e. before any pjax navigation. That way subsequent pjax pages can already count on it being loaded.

**Comment by staabm** [comment]
I guess using loaders like require.js would also help you to resolve the dependency issues

**Comment by page7** [comment]
Thanks

**Pull request closed without merging**
